name: cas_natal_app_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo_cas.png
    - assets/logo_cas_admin.png
    - assets/logo_cas_transparente.png

    - assets/avatar/menina.png
    - assets/avatar/menino.png
    - assets/avatar/menino2.png
    - assets/avatar/menina2.png

    - assets/modulos/cas.jpg
    - assets/modulos/diversidade.jpg
    - assets/modulos/letramento.png
    - assets/modulos/inclusao.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_cas_admin.png"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  image: assets/logo_cas_admin.png
